# Generated by Django 5.1.4 on 2025-01-08 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('NEGOTIATED', 'Negotiated'), ('NOT_CATALOGUED', 'Not Catalogued'), ('NOT_CATALOGUED', 'Not Catalogued')], max_length=100)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('APPROVING', 'Approving'), ('REJECTED', 'Rejected')], max_length=100)),
                ('date', models.DateTimeField()),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='finnecto.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='finnecto.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='finnecto.product')),
            ],
        ),
    ]
